<!DOCTYPE html>
<html lang="en">
<footer>
    <a
        href="https://team-web-dev.atlassian.net/jira/software/projects/TWD/boards/2?atlOrigin=eyJpIjoiYmU1MWY3MDQ3MGNlNDljZTlkZTlkYzkzYTRhNjA2MzQiLCJwIjoiaiJ9"
    >
        Visit our Jira workspace to find out more about our project management.
    </a>
    <br />
    <a
        href="https://github.com/Linkfinitive/TeamWebDevProject"
        target="_blank"
    >
        Visit our GitHub Repository.
    </a>
</footer>
</html>